### ISSUE TITLE
MCPTT Private Call Configuration

### ISSUE THREAD

**Issue by SAAFISalwa** [usnistgov/psc-ns3#15]
Hello,

I was checking the MCPTT examples that you provided and I only found a basic group call example.

I was trying to make a scenario of a private call but I didn't know how to configure it the same way as a basic group call (screenshot below).

So, can you please provide me with an example of MCPTT private call setup? if possible of course.

Thanks in advance.

![Capture](https://user-images.githubusercontent.com/60744742/89882202-c8f92480-dbc6-11ea-9e84-8f2ce064fb54.PNG)

**Comment by wdgj** [comment]
Hello,

[mcptt-lte-sl-out-of-covrg-comm.zip](https://github.com/usnistgov/psc-ns3/files/5132491/mcptt-lte-sl-out-of-covrg-comm.zip)

Attached is the updated example with a private call configured for two applications. Replacing the highlighted snippet with the following code is how you can configure a private call:

` ObjectFactory callFac;`
`  callFac.SetTypeId ("ns3::McpttCallMachinePrivate");`
`  ObjectFactory floorFac;`
`  floorFac.SetTypeId ("ns3::McpttFloorMachineBasic");`
`  for (uint32_t idx = 0; idx < clientApps.GetN (); idx++)`
`    {`
`      uint32_t targetId = 0;`
`      Ptr<McpttPttApp> pttApp = DynamicCast<McpttPttApp, Application> (clientApps.Get (idx));`
`      if (idx % 2 == 0)`
`        {`
`          targetId = idx + 2;`
`          pttApp->GetPusher ()->SetAttribute ("Automatic", BooleanValue (true));`
`        }`
`      callFac.Set ("TargetId", UintegerValue (targetId));`
`      callFac.Set ("TFP1", TimeValue (MilliSeconds (80)));`
`      pttApp->CreateCall (callFac, floorFac);`
`      pttApp->SelectLastCall ();`
`    }``

For call types other than a Basic Group Call, the call must be configured manually. Here you must use the object factories to configure the type of call. Next set the TargetId to the MCPTT user ID of the user that is to be called, and put the pusher in automatic mode so that it will randomly initiate the call and generate talk spurts through out the simulation (the original value of Automatic was changed to false when the applications where created with the MCPTT helper). Then you can also increase the value of TFP1 to allocate more time for the call setup to take place. Then the call is created and selected in the application for use after the simulation starts. Once the simulation completes, you should see information about the call activity in the "mcptt_msg_stats.txt" and "mcptt_state_machine_stats.txt" trace files

**Comment by SAAFISalwa** [comment]
Thanks for your answer!
